name: Gloo Nightly Tests
description: Runs tests with the nightly label
  
runs:
  using: "composite"
  steps:
  - name: Testing - nightly tests
    shell: bash
    run: make install-test-tools run-nightly-tests
  - name: save results
    if: ${{ failure() }}
    shell: bash
    run: mkdir -p _output/nightly-artifacts && echo '{"url":"https://github.com/solo-io/gloo/actions/runs/${{github.run_id}}",
            "name":"nightly"}' > _output/nightly-artifacts/test-out.json
  - uses: actions/upload-artifact@v3
    if: ${{ failure() }}
    with:
      name: nightly-dump
      path: "_output/nightly-artifacts"
      if-no-files-found: warn