name: "Reviewer lottery"
on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
    tags-ignore:
      - 'work in progress'
jobs:
  add-reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: uesteibar/reviewer-lottery@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}